#!/usr/bin/env zsh

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

alias ls="ls --color=auto"
alias v="nvim"
alias tzst="tar -c -v --zstd --options zstd:compression-level=19,zstd:threads=0 -f"

if [[ "$OSTYPE" == linux* ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

HOMEBREW_PREFIX="$(brew --prefix)"
source "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

source <(sk --shell zsh --shell-bindings)
eval "$(starship init zsh)"
