[tools]
neovim = "latest"
fzf = "latest"
bat = "latest"
ripgrep = "latest"
fd = "latest"
chezmoi = "latest"
tealdeer = "latest"
lazygit = "latest"
topgrade = "latest"
starship = "latest"
atuin = "latest"

